name: CI

on:
  push:
    branches:
      - main
  pull_request:

jobs:

  vet:
    name: Go vet code
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2

      - name: Set up Go
        uses: actions/setup-go@v2
        with:
          go-version: 1.17

      - name: Go vet code
        run: for d in */; do for f in $(ls $d/*.go); do go vet $f; done; done
